# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PUBLISH TO GITHUB PAGES

on:
  push:
    branches:
      - master
      - development
  schedule :
    - cron : '0 18 * * *' #UTC
#    - cron : '0 3 * * *' JST

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:      
    - uses: actions/checkout@v2
    - name: generate-data
      uses: actions/setup-node@v1
      with:
        node-version: v12.14.1
    - run: yarn --frozen-lockfile
      working-directory: ./tool
    - run: yarn gen
      working-directory: ./tool
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: yarn --frozen-lockfile
      working-directory: ./spa
    - run: yarn build-prod
      working-directory: ./spa
    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: upload-data
        path: ./spa/dist/prod
  push:
    needs: build
    name: push-data
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     ref: master
      #     path: site
      - name: upload
        uses: actions/download-artifact@v1
        with:
          name: upload-data
      - run: cp upload-data/* ./site/docs
      - run: git config --global user.email "bot@github.com"
      - run: git config --global user.name "BOT"
      - run: cd site && git add ./docs
      - run: cd site && git commit -m "update data"
      - run: cd site && git push origin data