# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: ./spa
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    steps:      
    - uses: actions/checkout@v2
    - name: Deploy to prod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      uses: actions/setup-node@v1
      with:
        node-version: v12.14.1
    - run: echo ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - run: yarn --frozen-lockfile
      working-directory: ./tool
    - run: yarn gen
      working-directory: ./tool
    - run: yarn --frozen-lockfile
    - run: yarn deploy-prod
